/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:controlWindow:808884:
  appc.background(230);
} //_CODE_:controlWindow:808884:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:option1:288886:
  println("Shader = Gouraud");
  theShader = gouraudShader;
} //_CODE_:option1:288886:

public void option2_clicked1(GOption source, GEvent event) { //_CODE_:option2:809986:
  println("Shader = Phong");
  theShader = phongShader;
} //_CODE_:option2:809986:

public void option3_clicked1(GOption source, GEvent event) { //_CODE_:option3:210577:
  println("Shader = Flat");
  theShader = flatShader;
} //_CODE_:option3:210577:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  controlWindow = new GWindow(this, "Control Window", 0, 0, 340, 220, false, JAVA2D);
  controlWindow.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(controlWindow.papplet, -10, 10, 80, 20);
  label1.setText("Shader");
  label1.setOpaque(false);
  togGroup1 = new GToggleGroup();
  option1 = new GOption(controlWindow.papplet, 80, 10, 120, 20);
  option1.setText("Gouraud");
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  option2 = new GOption(controlWindow.papplet, 80, 40, 120, 20);
  option2.setText("Phong");
  option2.setOpaque(false);
  option2.addEventHandler(this, "option2_clicked1");
  option3 = new GOption(controlWindow.papplet, 80, 70, 120, 20);
  option3.setText("Flat");
  option3.setOpaque(false);
  option3.addEventHandler(this, "option3_clicked1");
  togGroup1.addControl(option1);
  option1.setSelected(true);
  togGroup1.addControl(option2);
  togGroup1.addControl(option3);
}

// Variable declarations 
// autogenerated do not edit
GWindow controlWindow;
GLabel label1; 
GToggleGroup togGroup1; 
GOption option1; 
GOption option2; 
GOption option3; 

