/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(GWinApplet appc, GWinData data) { //_CODE_:controlwindow:733559:
  appc.background(230);
} //_CODE_:controlwindow:733559:

public void img1_clicked1(GOption source, GEvent event) { //_CODE_:img1:354219:
//  println("img1 - GOption >> GEvent." + event + " @ " + millis());
  image = one;
} //_CODE_:img1:354219:

public void img2_clicked1(GOption source, GEvent event) { //_CODE_:img2:871738:
//  println("img2 - GOption >> GEvent." + event + " @ " + millis());
  image = two;
} //_CODE_:img2:871738:

public void option1_clicked1(GOption source, GEvent event) { //_CODE_:option1:345520:
//  println("option1 - GOption >> GEvent." + event + " @ " + millis());
  image = three;
} //_CODE_:option1:345520:

public void img4_clicked1(GOption source, GEvent event) { //_CODE_:img4:616017:
//  println("img4 - GOption >> GEvent." + event + " @ " + millis());
  image = four;
} //_CODE_:img4:616017:

public void img5_clicked1(GOption source, GEvent event) { //_CODE_:img5:558847:
//  println("img5 - GOption >> GEvent." + event + " @ " + millis());
  image = five;
} //_CODE_:img5:558847:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  controlwindow = new GWindow(this, "Control Window", 0, 0, 340, 220, false, JAVA2D);
  controlwindow.setActionOnClose(G4P.EXIT_APP);
  controlwindow.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(controlwindow.papplet, 14, 15, 80, 20);
  label1.setText("Image Select");
  label1.setOpaque(false);
  togGroup1 = new GToggleGroup();
  img1 = new GOption(controlwindow.papplet, 105, 15, 120, 20);
  img1.setText("One");
  img1.setOpaque(false);
  img1.addEventHandler(this, "img1_clicked1");
  img2 = new GOption(controlwindow.papplet, 105, 45, 120, 20);
  img2.setText("Two");
  img2.setOpaque(false);
  img2.addEventHandler(this, "img2_clicked1");
  option1 = new GOption(controlwindow.papplet, 105, 75, 120, 20);
  option1.setText("Three");
  option1.setOpaque(false);
  option1.addEventHandler(this, "option1_clicked1");
  img4 = new GOption(controlwindow.papplet, 105, 105, 120, 20);
  img4.setText("Four");
  img4.setOpaque(false);
  img4.addEventHandler(this, "img4_clicked1");
  img5 = new GOption(controlwindow.papplet, 105, 135, 120, 20);
  img5.setText("Five");
  img5.setOpaque(false);
  img5.addEventHandler(this, "img5_clicked1");
  togGroup1.addControl(img1);
  togGroup1.addControl(img2);
  togGroup1.addControl(option1);
  option1.setSelected(true);
  togGroup1.addControl(img4);
  togGroup1.addControl(img5);
}

// Variable declarations 
// autogenerated do not edit
GWindow controlwindow;
GLabel label1; 
GToggleGroup togGroup1; 
GOption img1; 
GOption img2; 
GOption option1; 
GOption img4; 
GOption img5; 

